### PR TITLE
run as normal user, include icons in project, update .Net to 4.6.1

### PR DESCRIPTION
**Pull request by oltolm**
This includes several fixes:

1. app does not run as admin any more
1. I have included the icons in the VS project
1. I have update .Net to 4.6.1

### CODE REVIEW

**Comment by uberhalit** [comment]
Hello, 

sorry for the long delay, I am not using this account much.

Unfortunately I'll have to decline your PR:

1. Administrator rights are required to inject code into another prcesses' memory regardless of elevation. If Sekiro runs as admin then the app won't even be able to read memory.
2. The Icon is not mine so afaik I am only allowed to redistribute it with the compiled version of my app but not in .ico form on github.
3.  Updating to 4.6.1 is not neccessary as I am not using anything from 4.6.1. 4.6 is part of every Windows 10 and Windows 8.1 install so we don't need to worry about it.

Greetings

**Comment by oltolm** [comment]
>Administrator rights are required to inject code into another prcesses' memory regardless of elevation. If Sekiro runs as admin then the app won't even be able to read memory.
I don't understand what you mean. I tested your app and it works when started as normal user. The elevation prompt is unnecessary and just annoying because I have to enter my password. No other app of this kind has an elevation prompt. Regardless thanks for making this open source. I fixed the problem for myself.

**Comment by uberhalit** [comment]
Hello, 
the app will start just fine but if you activate any option that injects a code cave then the patching process will fail due to insufficient privileges, at least that’s the case on an ordinary Windows 10 install. It is possible to allow patching without admin rights but that is not the default setup of Windows 10.

**Comment by oltolm** [comment]
> 
> 
> Hello,
> the app will start just fine but if you activate any option that injects a code cave then the patching process will fail due to insufficient privileges, at least that’s the case on an ordinary Windows 10 install. It is possible to allow patching without admin rights but that is not the default setup of Windows 10.

I don't believe it because it works fine and I don't remember allowing patching. Doesn't matter anyway because I solved my problem.

**Pull request closed without merging**
